In [278]:
import numpy as np
import networkx as nx

def compute_phi(r, Rbar, obar, e, o):
    # Rbar is the (n x n) matrix of obligations with i being rows and j columns (edge from i to j: R[i,j] = 1)
    # R is a payment clearing vector
    
    # obligations from others to i are given by the product of nominal obligations 
    # matrix Rbar and payment vector R
    _R = np.asarray(np.matmul(Rbar,r)).reshape(-1)
    
    if True:
        print("r =",r, "_R =", _R)
    
    # Return: Construct new vector r with obligations from each component to the rest of the system
    _r = np.zeros((3), dtype=float)
    
    for i in range(0,len(R)):
        # What node i receives from node j is either Rbar or zero
        _Rbari = np.sum(Rbar[:,i])  # what i owes others nominally
        _Rbarj = np.sum(Rbar[i,:])  # what i is owed from others nominally
        _Rj = _R[i] # what others actually pay to i
        
        _vi = e[i] + (o[i] - obar[i]) + (_Rj - _Rbarj)
        
        print(i, "|", r[i], _Rbari, "|", e[i], o[i], obar[i], "|", _Rbarj, _Rj, _vi)
        
        if _vi <= 0.0:
            _r[i] = 0
        else:
            _r[i] = _Rbari
         
    return _r

# CREATE NETWORK
G = nx.MultiDiGraph()

G.add_node(0)
G.add_node(1)
G.add_node(2)

G.add_edge(0,1, weight=1)  # 0 --> 1 : obligation 1 has to 0, by convention
G.add_edge(1,2, weight=1)  
G.add_edge(2,0, weight=0)

# CREATE SYSTEM
e = np.array([0.1, 0.1, 0.1])

obar = np.array([1.0, 1.0, 1.0])
o = np.array([1.0, 1.0, 1.0])  # this is changed later to trigger a shock

Rbar = nx.to_numpy_matrix(G)

r = np.array([0.0, 1.0, 1.0]) # np.zeros((3), dtype=float)

if True:
    print("Rbar = \n", Rbar, "\n")
    print("r =", r, "\n---------------------------\n")
    print("i | r[i] _Rbari | e[i] o[i] obar[i] | _Rbarj _Rj _vi\n\n")
    
for j in range(0,10):
    r = compute_phi(r, Rbar, obar, e, o)
    print("r =", r, "\n")


Rbar = 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]] 

r = [0. 1. 1.] 
---------------------------

i | r[i] _Rbari | e[i] o[i] obar[i] | _Rbarj _Rj _vi


r = [0. 1. 1.] _R = [1. 1. 0.]
0 | 0.0 0.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
1 | 1.0 1.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
2 | 1.0 1.0 | 0.1 1.0 1.0 | 0.0 0.0 0.1
r = [0. 1. 1.] 

r = [0. 1. 1.] _R = [1. 1. 0.]
0 | 0.0 0.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
1 | 1.0 1.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
2 | 1.0 1.0 | 0.1 1.0 1.0 | 0.0 0.0 0.1
r = [0. 1. 1.] 

r = [0. 1. 1.] _R = [1. 1. 0.]
0 | 0.0 0.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
1 | 1.0 1.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
2 | 1.0 1.0 | 0.1 1.0 1.0 | 0.0 0.0 0.1
r = [0. 1. 1.] 

r = [0. 1. 1.] _R = [1. 1. 0.]
0 | 0.0 0.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
1 | 1.0 1.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
2 | 1.0 1.0 | 0.1 1.0 1.0 | 0.0 0.0 0.1
r = [0. 1. 1.] 

r = [0. 1. 1.] _R = [1. 1. 0.]
0 | 0.0 0.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
1 | 1.0 1.0 | 0.1 1.0 1.0 | 1.0 1.0 0.1
2 | 1.0 1.0 | 0.1 1.0 1.0 | 0.0 0.0 0.1
r = [0. 1. 1.] 

r = [0. 1. 1